version: "3.7"

volumes:
    postgres-data:
    minio-data:

services:
    web:
        image: ghcr.io/speedpuzzling/web-base:main
        restart: unless-stopped
        volumes:
            - .:/app
            - .docker/on-startup.sh:/docker-entrypoint.d/on-startup.sh
        depends_on:
            - postgres
        ports:
            - "8080:8080"
        environment:
            XDEBUG_CONFIG: "client_host=host.docker.internal"
            XDEBUG_MODE: debug
            PHP_IDE_CONFIG: "serverName=speedpuzzling"

    postgres:
        image: postgres:16.0
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: speedpuzzling
        volumes:
            - postgres-data:/var/lib/postgresql/data
        ports:
            - "5432:5432"

    js-watch:
        image: ghcr.io/speedpuzzling/web-base:main
        volumes:
            - .:/app
        restart: unless-stopped
        entrypoint: [""]
        command: ["bash", "-c", "npm install && npm run watch"]

    adminer:
        image: adminer:4.8.0
        ports:
            - "8000:8080"
        environment:
            ADMINER_DEFAULT_SERVER: postgres
        depends_on:
            - postgres

    minio:
        restart: always
        image: minio/minio:latest
        environment:
            MINIO_DOMAIN: "localhost:19000"
            MINIO_SERVER_URL: "http://minio:9000"
            MINIO_BROWSER_REDIRECT_URL: "http://localhost:19001"
            MINIO_ROOT_USER: speedpuzzling
            MINIO_ROOT_PASSWORD: speedpuzzling
        command: ["server", "/data", "--console-address", ":9001"]
        ports:
            - 19000:9000
            - 19001:9001
        volumes:
            - minio-data:/data
