version: "3.7"

volumes:
    postgres-data:

services:
    web:
        build:
            context: .
            target: base
        restart: unless-stopped
        volumes:
            - .:/app
            - .docker/nginx-unit:/docker-entrypoint.d
        depends_on:
            - postgres
        ports:
            - "8080:8080"
        environment:
            XDEBUG_CONFIG: "client_host=host.docker.internal"
            XDEBUG_MODE: debug
            PHP_IDE_CONFIG: "serverName=speedpuzzling"

    postgres:
        image: postgres:16.0
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: ppeedpuzzling
        volumes:
            - postgres-data:/var/lib/postgresql/data
        ports:
            - "5432:5432"

    js-watch:
        image: node:16
        volumes:
            - .:/app
        working_dir: /app
        restart: unless-stopped
        entrypoint: [""]
        command: ["bash", "-c", "npm install && npm run watch"]

    adminer:
        image: adminer:4.8.0
        ports:
            - "8000:8080"
        environment:
            ADMINER_DEFAULT_SERVER: postgres
        depends_on:
            - postgres
