<?php

declare(strict_types=1);

namespace SpeedPuzzling\Web\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 *
 * Generated by doctrine:migrations:diff; the statements for user_account and
 * reset_password_request that the diff also produced were dropped - those tables
 * ship in Version20260724073022 / Version20260724110010, which were simply not
 * applied to the development database yet.
 */
final class Version20260724185519 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Native auth (issue #147): login_link_request table making magic sign-in links single-use (D18)';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE login_link_request (consumed_at TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, id UUID NOT NULL, hashed_token VARCHAR(255) NOT NULL, requested_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, expires_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, user_account_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8D22165ABD2BA26B ON login_link_request (hashed_token)');
        $this->addSql('CREATE INDEX IDX_8D22165A3C0C9956 ON login_link_request (user_account_id)');
        $this->addSql('ALTER TABLE login_link_request ADD CONSTRAINT FK_8D22165A3C0C9956 FOREIGN KEY (user_account_id) REFERENCES user_account (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE login_link_request DROP CONSTRAINT FK_8D22165A3C0C9956');
        $this->addSql('DROP TABLE login_link_request');
    }
}
