<?php

declare(strict_types=1);

namespace SpeedPuzzling\Web\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Activity analytics (docs/features/activity-analytics.md): raw per-player
 * daily presence + immortal per-locale daily aggregates.
 *
 * Auto-generated by doctrine:migrations:diff; the auth_audit_log statements the
 * diff duplicated (dev DB had not run Version20260731113901 yet) were removed.
 */
final class Version20260731121500 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE activity_daily_summary (id UUID NOT NULL, day DATE NOT NULL, locale VARCHAR(10) NOT NULL, active_players INT NOT NULL, active_members INT NOT NULL, new_registrations INT NOT NULL, computed_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_101B7E53E5A029904180C698 ON activity_daily_summary (day, locale)');
        $this->addSql('CREATE TABLE player_activity_day (id UUID NOT NULL, day DATE NOT NULL, first_seen_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, player_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_17A4E73099E6F5DF ON player_activity_day (player_id)');
        $this->addSql('CREATE INDEX IDX_17A4E730E5A02990 ON player_activity_day (day)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_17A4E73099E6F5DFE5A02990 ON player_activity_day (player_id, day)');
        $this->addSql('ALTER TABLE player_activity_day ADD CONSTRAINT FK_17A4E73099E6F5DF FOREIGN KEY (player_id) REFERENCES player (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE player_activity_day DROP CONSTRAINT FK_17A4E73099E6F5DF');
        $this->addSql('DROP TABLE activity_daily_summary');
        $this->addSql('DROP TABLE player_activity_day');
    }
}
